#pragma once

enum
{
    PERF_TUD_TASK,
    PERF_CDC_FLUSH,
    PROF_MIXOUT_USBDATA,
    PROF_MIXOUT_LINEIN_FETCH,
    PROF_MIXOUT_LINEIN_MIX,
    PROF_MIXOUT_SPDIF_WRITE,
    PROF_MIXOUT_DAC_WRITE,
    PROF_MIXIN_ADC_FETCH,
    PROF_MIXIN_ADC_MIX,
    PROF_MIXIN_SPDIF_FETCH,
    PROF_MIXIN_SPDIF_MIX,
    PROF_CONV_IP_APPLY,
    PROF_CONV_APPLY,
    PROF_DWSMP_IP_SETUP,
    PROF_DWSMP_IP_LOOP,
    PROF_DWSMP_IP_SAVE,
    PROF_DWSMP_SETUP,
    PROF_DWSMP_LOOP,
    PROF_DWSMP_SAVE,
    PROF_UPSMP_IP_SETUP,
    PROF_UPSMP_IP_LOOP,
    PROF_UPSMP_IP_SAVE,
    PROF_UPSMP_SETUP,
    PROF_UPSMP_LOOP,
    PROF_UPSMP_SAVE,

    MAX_MEASUREMENT
};